alter table news
drop column author;

alter table news
    add "authorId" integer not null;

-- column reordering is not supported news."authorId"

create table authors
(
    "authorId" integer generated by default as identity
        primary key,
    name       varchar(64) not null,
    email      varchar(64) not null,
    "statusId" integer     not null
        constraint "Ref_authors_to_statuses"
            references statuses
);

alter table authors
    owner to postgres;

alter table news
    add constraint "Ref_news_to_authors"
        foreign key ("authorId") references authors;

